import { Vacancy, PipelineStage, Profile, AgentConfig } from './types';

export const mockVacancies: Vacancy[] = [
  {
    id: '1',
    company_id: 'c1',
    company_name: 'Яндекс',
    company_site: 'https://yandex.ru',
    role: 'Senior Frontend Developer',
    salary: '300 000 - 400 000 ₽',
    status: 'interview',
    source: 'HH',
    score: 85,
    category: 'горячая',
    reason: 'Отличное совпадение по навыкам React, TypeScript.',
    letter: 'Здравствуйте! Меня заинтересовала ваша вакансия Senior Frontend Developer...',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    company_id: 'c2',
    company_name: 'VK',
    company_site: 'https://vk.company',
    role: 'React Developer',
    salary: '250 000 - 350 000 ₽',
    status: 'sent',
    source: 'TG',
    score: 75,
    category: 'горячая',
    reason: 'Хорошее совпадение по стеку. Интересные проекты.',
    letter: 'Добрый день! Увидел вакансию React Developer в VK...',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    company_id: 'c3',
    company_name: 'Тинькофф',
    role: 'Frontend Engineer',
    salary: '280 000 - 380 000 ₽',
    status: 'replied',
    source: 'HH',
    score: 92,
    category: 'горячая',
    reason: 'Идеальное совпадение. Современный стек, высокая зарплата.',
    letter: 'Здравствуйте! Рассматриваю позицию Frontend Engineer в Тинькофф...',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    company_id: 'c4',
    company_name: 'Сбер',
    role: 'JavaScript Developer',
    salary: '200 000 - 300 000 ₽',
    status: 'new',
    source: 'LinkedIn',
    score: 55,
    category: 'норм',
    reason: 'Зарплата ниже ожиданий, но интересный проект.',
    letter: 'Добрый день! Интересуюсь позицией JavaScript Developer...',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    company_id: 'c5',
    company_name: 'Авито',
    role: 'Senior React Developer',
    salary: '320 000 - 420 000 ₽',
    status: 'new',
    source: 'HH',
    score: 88,
    category: 'горячая',
    reason: 'Отличная зарплата, современный стек, большая команда.',
    letter: 'Здравствуйте! Хочу откликнуться на вакансию Senior React Developer...',
    published_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    company_id: 'c6',
    company_name: 'OZON',
    role: 'Frontend Developer',
    salary: '240 000 - 320 000 ₽',
    status: 'rejected',
    source: 'HH',
    score: 65,
    category: 'норм',
    reason: 'Средний уровень совпадения, зарплата приемлемая.',
    letter: 'Здравствуйте! Меня заинтересовала позиция Frontend Developer...',
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockPipelineStages: PipelineStage[] = [
  { id: 's1', name: 'Новые', order_index: 1, color: '#6B7280' },
  { id: 's2', name: 'Отправлено', order_index: 2, color: '#3B82F6' },
  { id: 's3', name: 'Ответ', order_index: 3, color: '#EAB308' },
  { id: 's4', name: 'Интервью', order_index: 4, color: '#22C55E' },
  { id: 's5', name: 'Оффер', order_index: 5, color: '#F59E0B' },
  { id: 's6', name: 'Отказ', order_index: 6, color: '#EF4444' },
];

export const mockProfile: Profile = {
  id: 'p1',
  content: 'Senior Frontend Developer с 7+ годами опыта. Специализация: React, TypeScript, современные подходы к разработке.',
};

export const mockAgentConfig: AgentConfig = {
  id: 'ag1',
  name: 'scorer',
  system_prompt: '',
  params: { min_salary: 0, work_formats: [], stop_words: [] },
};
